### ISSUE TITLE
Broken regexes

### ISSUE THREAD

**Issue by ojensen5115** [veorq/blueflower#6]
Two of the regex matches are `private[ -_]key` and `secret[ -_]key`. The character range `[ -_]` matches ` !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^`, so this will match a number of undesired tokens.

I suspect this should be `[ \-_]` or simply `[ _-]`

**Comment by veorq** [comment]
Thanks, overlooked that! Fixed in https://github.com/veorq/blueflower/commit/d0cb79781819e12e309562a9f66a09a52493e0aa
